name: Check

on:
  pull_request:
    paths:
      - .github/workflows/check.yml
      - Cargo.*
      - "**/*.rs"

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  clippy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: docker://rust:1.65-bullseye
    steps:
      - run: rustup component add clippy
      - uses: olix0r/cargo-action-fmt@ee1ef42932e44794821dab57ef1bf7a73df8b21f
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - run: cargo clippy --all-targets --all-features --message-format=json | cargo-action-fmt

  fmt:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: docker://rust:1.65-bullseye
    steps:
      - run: rustup component add rustfmt
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - run: cargo fmt -- --check
